import assert from 'node:assert/strict';
import { createCoach } from './coach.js';
import { createShift } from './shift.js';
import { DAYS, STARTING_MENU } from './data.js';

const element = () => ({ style: {}, dataset: {}, textContent: '', addEventListener() {} });
const bubble = element();
const kicker = element();
const text = element();
const coach = createCoach({ bubble, kicker, text, okButton: element(), skipButton: element(), scene: { atStation: null, setGuide() {} }, announce() {} });
const shift = createShift({ day: DAYS[0], seed: 1, menu: STARTING_MENU });
coach.start(shift, { withTutorial: true });
shift.tick(2);
coach.frame();
assert.equal(shift.state.hold, true, 'first customer holds the tutorial clock');
shift.state.oven[0] = { item: { stage: 'burnt' } };
coach.frame();
assert.match(text.textContent, /Take out \(burnt!\)/, 'recover a burnt cupcake still in the oven');
shift.state.oven[0] = null;
shift.state.display[0] = { stage: 'baked' };
coach.frame();
assert.match(text.textContent, /Display Case/, 'recover a stored tutorial cupcake');
shift.state.busy = { label: 'Vanilla batter', stationId: 'cafeTable' };
coach.frame();
assert.match(text.textContent, /Wait for the action to finish/, 'explain why station clicks are temporarily unavailable');
shift.state.busy = null;
shift.state.jammed.add('oven');
coach.frame();
assert.match(text.textContent, /Cool it down/, 'recover a jammed tutorial station');
coach.onEvent({ type: 'served' });
assert.equal(shift.state.hold, false, 'serving resumes the day clock');
assert.equal(coach.tutorialActive, false);
console.log('7 tutorial regression checks passed');
