import assert from 'node:assert/strict';
import { recipeStepsFor } from './ui.js';
const state = { hands: [], oven: [], customers: [{ order: { flavor: 'vanilla', frosting: 'buttercream', topping: 'sprinkles' }, toGo: true }] };
const done = (label) => recipeStepsFor(state).steps.find(([name]) => name === label)?.[1];
assert.equal(recipeStepsFor(state).steps.some(([, complete]) => complete), false);
const item = { flavor: 'vanilla', stage: 'raw', frosting: null, topping: null, boxed: false };
state.hands.push(item);
assert.equal(done('Batter'), true);
assert.equal(done('Bake'), false);
state.hands = []; item.stage = 'baking'; state.oven = [{ item }];
assert.equal(done('Bake'), false);
item.stage = 'baked';
assert.equal(done('Bake'), true);
assert.equal(done('Take out'), false);
assert.equal(done('Frost'), false);
state.oven = []; state.hands.push(item);
assert.equal(done('Take out'), true);
item.frosting = 'buttercream';
assert.equal(done('Frost'), true);
assert.equal(done('Topping'), false);
item.topping = 'sprinkles';
assert.equal(done('Topping'), true);
assert.equal(done('Box'), false);
item.boxed = true;
assert.equal(done('Box'), true);
assert.equal(done('Serve'), false);
state.hands = [];
assert.equal(recipeStepsFor(state).steps.some(([, complete]) => complete), false);
console.log('Recipe progress checks passed: empty, raw, baking, pickup, frosting, topping, boxing, and reset');
