export const GAME_WIDTH = 960;
export const GAME_HEIGHT = 540;

export const BAKERY_STATIONS = {
  cafeTable: { label: "Link 1 · Spark", contentKey: "about" },
  recipeBook: { label: "Link 2 · Fizz", contentKey: "skills" },
  displayCase: { label: "Link 3 · Load", contentKey: "projects" },
  oven: { label: "Link 4 · Heat", contentKey: "resume" },
  frostingCounter: { label: "Link 5 · Swirl", contentKey: "technologies" },
  decoratingCounter: { label: "Link 6 · Sparkle", contentKey: "featuredProject" },
  deliveryStation: { label: "Link 7 · Wrap", contentKey: "github" },
  bakeryDoor: { label: "Link 8 · Payoff", contentKey: "contact" },
};

export const CUPCAKE_STEPS = [
  {
    id: "ingredients",
    number: 1,
    station: "Ingredients",
    stationId: "cafeTable",
    questLabel: "Gather the Ingredients",
    triggers: "Batter",
    instruction: "Visit the ingredients station.",
    completionMessage: "Four ingredients in - the first domino tips over.",
    content: "Every chain reaction needs a spark. These ingredients start a chain that runs all the way to the customer.",
    link: null,
    interactionType: "arrival",
    ingredientItems: [
      { id: "egg", label: "Eggs", fact: "Eggs bind everything. Skip them and the batter falls apart two stations later." },
      { id: "butter", label: "Butter", fact: "Butter traps air - the oven turns that air into rise." },
      { id: "flour", label: "Flour", fact: "Flour builds the structure the frosting will sit on." },
      { id: "sugar", label: "Sugar", fact: "Sugar browns in the oven: one ingredient, three stations of effect." },
    ],
  },
  {
    id: "batter",
    number: 2,
    station: "Batter",
    stationId: "recipeBook",
    questLabel: "Mix the Batter",
    triggers: "Assembly",
    instruction: "Head to the mixing station.",
    completionMessage: "The batter is mixed - the reaction spreads to the tray.",
    content: "Mixing kicks off real chemistry: baking soda and acid start fizzing the moment they meet.",
    link: null,
    interactionType: "arrival",
  },
  {
    id: "tray",
    number: 3,
    station: "Assembly",
    stationId: "displayCase",
    questLabel: "Fill the Cupcake Tray",
    triggers: "Oven",
    instruction: "Visit the assembly station.",
    completionMessage: "Tray filled - the heat is next in line.",
    content: "Every cup you fill here is a cupcake the oven has to bake. What goes in here ripples through every later station.",
    link: null,
    interactionType: "arrival",
  },
  {
    id: "baking",
    number: 4,
    station: "Baking",
    stationId: "oven",
    questLabel: "Bake the Cupcakes",
    triggers: "Frosting",
    instruction: "Bring the tray to the oven.",
    completionMessage: "Baked! The rise is locked in - frosting is up next.",
    content: "Heat sets off the rise: tiny gas bubbles expand and the cupcakes puff up.",
    link: null,
    interactionType: "arrival",
  },
  {
    id: "frosting",
    number: 5,
    station: "Frosting",
    stationId: "frostingCounter",
    questLabel: "Frost the Cupcakes",
    triggers: "Decorating",
    instruction: "Visit the frosting station, then tap to frost.",
    completionMessage: "Perfectly frosted - the decorating station lights up.",
    content: "Frosting only sets on a cooled, risen cupcake - it depends on every link before it.",
    link: null,
    interactionType: "button",
  },
  {
    id: "decorating",
    number: 6,
    station: "Decorating",
    stationId: "decoratingCounter",
    questLabel: "Add the Decorations",
    triggers: "Packaging",
    instruction: "Visit the decorating station.",
    completionMessage: "Sprinkles on - the order rolls on to packaging.",
    content: "Each decoration you add changes how the order has to be packed.",
    link: null,
    interactionType: "arrival",
  },
  {
    id: "packaging",
    number: 7,
    station: "Packaging",
    stationId: "deliveryStation",
    questLabel: "Package the Order",
    triggers: "Serving",
    instruction: "Bring the cupcakes to the packaging station.",
    completionMessage: "Boxed and bowed - the final link is ready.",
    content: "Packaging is the last link before the customer. A slip here undoes the whole chain.",
    link: null,
    interactionType: "arrival",
  },
  {
    id: "serving",
    number: 8,
    station: "Serving",
    stationId: "bakeryDoor",
    questLabel: "Serve the Customer",
    triggers: "A happy customer",
    instruction: "Deliver the finished order.",
    completionMessage: "Served! One order set off eight stations in a row - that is a chain reaction.",
    content: "The last domino: one order, eight stations, one happy customer.",
    link: null,
    interactionType: "arrival",
  },
];

export const COLORS = {
  cream: "#f8edd8",
  parchment: "#f2d6ad",
  pink: "#e9a6a4",
  red: "#ad4d4b",
  brown: "#623f36",
  golden: "#f0c96b",
  cocoa: "#3d2929",
  sage: "#9eaf87",
};
